_wandb:
    value:
        cli_version: 0.22.3
        e:
            xltvdol9anlxkx3us29k7ntu2uqrnddb:
                codePath: neural_network.py
                codePathLocal: neural_network.py
                email: xhanushchak@stuba.sk
                executable: D:\University\zneus\ZNEUS-Projekt1\.venv\Scripts\python.exe
                git:
                    commit: 6d1fdc7eff6a130bc939a0f2fb5db4b83b35241d
                    remote: https://github.com/NiceeTV/ZNEUS-Projekt1.git
                host: DESKTOP-473981L
                os: Windows-10-10.0.19044-SP0
                program: D:\University\zneus\ZNEUS-Projekt1\neural_network.py
                python: CPython 3.12.4
                root: D:\University\zneus\ZNEUS-Projekt1
                startedAt: "2025-11-06T20:47:58.116950Z"
                writerId: xltvdol9anlxkx3us29k7ntu2uqrnddb
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.4
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 256
dataset_path:
    value: data/transformed/small
epoch:
    value: 20
loss_fn:
    value: MSELoss
lr:
    value: 0.001
