_wandb:
    value:
        cli_version: 0.22.3
        e:
            edf6zy0lg8eqzdgpseugav4jztti5049:
                codePath: neural_network.py
                codePathLocal: neural_network.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "524287995904"
                        used: "191572250624"
                email: xhanushchak@stuba.sk
                executable: D:\University\zneus\ZNEUS-Projekt1\.venv\Scripts\python.exe
                git:
                    commit: 6d1fdc7eff6a130bc939a0f2fb5db4b83b35241d
                    remote: https://github.com/NiceeTV/ZNEUS-Projekt1.git
                gpu: NVIDIA GeForce GTX 1660 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1536
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660 Ti
                      uuid: GPU-bc3209b7-0fa3-1a21-9352-4a2a6218e968
                host: DESKTOP-473981L
                memory:
                    total: "16556679168"
                os: Windows-10-10.0.19044-SP0
                program: D:\University\zneus\ZNEUS-Projekt1\neural_network.py
                python: CPython 3.12.4
                root: D:\University\zneus\ZNEUS-Projekt1
                startedAt: "2025-11-06T20:32:32.639908Z"
                writerId: edf6zy0lg8eqzdgpseugav4jztti5049
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.4
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 256
dataset_path:
    value: data/transformed/full_features
epoch:
    value: 10
loss_fn:
    value: MSELoss
lr:
    value: 0.001
